// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tree_edit_distance
NumericVector tree_edit_distance(IntegerVector parent_vec_1, IntegerVector child_1_vec_1, IntegerVector child_2_vec_1, NumericVector weight_vec_1, IntegerVector parent_vec_2, IntegerVector child_1_vec_2, IntegerVector child_2_vec_2, NumericVector weight_vec_2);
RcppExport SEXP _fdMTED_tree_edit_distance(SEXP parent_vec_1SEXP, SEXP child_1_vec_1SEXP, SEXP child_2_vec_1SEXP, SEXP weight_vec_1SEXP, SEXP parent_vec_2SEXP, SEXP child_1_vec_2SEXP, SEXP child_2_vec_2SEXP, SEXP weight_vec_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec_1(parent_vec_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_1_vec_1(child_1_vec_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_2_vec_1(child_2_vec_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight_vec_1(weight_vec_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec_2(parent_vec_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_1_vec_2(child_1_vec_2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_2_vec_2(child_2_vec_2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight_vec_2(weight_vec_2SEXP);
    rcpp_result_gen = Rcpp::wrap(tree_edit_distance(parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1, parent_vec_2, child_1_vec_2, child_2_vec_2, weight_vec_2));
    return rcpp_result_gen;
END_RCPP
}
// get_prepross_tree
List get_prepross_tree(IntegerVector parent_vec_1, IntegerVector child_1_vec_1, IntegerVector child_2_vec_1, NumericVector weight_vec_1);
RcppExport SEXP _fdMTED_get_prepross_tree(SEXP parent_vec_1SEXP, SEXP child_1_vec_1SEXP, SEXP child_2_vec_1SEXP, SEXP weight_vec_1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec_1(parent_vec_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_1_vec_1(child_1_vec_1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_2_vec_1(child_2_vec_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight_vec_1(weight_vec_1SEXP);
    rcpp_result_gen = Rcpp::wrap(get_prepross_tree(parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fdMTED_tree_edit_distance", (DL_FUNC) &_fdMTED_tree_edit_distance, 8},
    {"_fdMTED_get_prepross_tree", (DL_FUNC) &_fdMTED_get_prepross_tree, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdMTED(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
