# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_edit_distance <- function(parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1, parent_vec_2, child_1_vec_2, child_2_vec_2, weight_vec_2) {
    .Call(`_fdMTED_tree_edit_distance`, parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1, parent_vec_2, child_1_vec_2, child_2_vec_2, weight_vec_2)
}

get_prepross_tree <- function(parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1) {
    .Call(`_fdMTED_get_prepross_tree`, parent_vec_1, child_1_vec_1, child_2_vec_1, weight_vec_1)
}

